name: note_taking_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.1
  google_fonts: ^4.0.1
  image_picker: ^0.8.6+1
  meta: ^1.8.0
  supabase_flutter: ^1.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
